apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoyoweb
  labels:
    name: hoyoweb
spec:
  selector:
    matchLabels:
      name: hoyoweb
  template:
    metadata:
      labels:
        name: hoyoweb
    spec:
      containers:
        - name: hoyoweb
          image: hoyo
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
